[server]
port = 8082

[theme]
base="dark"
primaryColor="purple"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
#font="sans serif"  ['sans serif', 'serif', 'monospace'].
font="serif"
